// Auto-generated by deploy script — or fill manually after deployment
// Replace these with your actual deployed contract addresses on Sepolia

export const CONTRACT_ADDRESSES = {
  taskManager: process.env.NEXT_PUBLIC_TASK_MANAGER_ADDRESS ?? "0x0000000000000000000000000000000000000000",
  bidManager: process.env.NEXT_PUBLIC_BID_MANAGER_ADDRESS ?? "0x0000000000000000000000000000000000000000",
  matchingEngine: process.env.NEXT_PUBLIC_MATCHING_ENGINE_ADDRESS ?? "0x0000000000000000000000000000000000000000",
} as const;

// ─── TaskManager ABI ─────────────────────────────────────────────────────────
export const TASK_MANAGER_ABI = [
  {
    name: "createTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "category", type: "string" },
      { name: "encryptedBudgetInput", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getTask",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "category", type: "string" },
      { name: "createdAt", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "bidCount", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "revealedWinningBid", type: "uint256" },
    ],
  },
  {
    name: "getActiveTasks",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    name: "taskCounter",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "cancelTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "TaskCreated",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "title", type: "string", indexed: false },
      { name: "category", type: "string", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    name: "WinnerRevealed",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "winningBid", type: "uint256", indexed: false },
    ],
  },
] as const;

// ─── BidManager ABI ──────────────────────────────────────────────────────────
export const BID_MANAGER_ABI = [
  {
    name: "submitBid",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "uint256" },
      { name: "encryptedBidInput", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
      { name: "deliveryDays", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "getBidCount",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getTaskProviders",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    name: "hasBid",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "taskId", type: "uint256" },
      { name: "provider", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getBidDeliveryDays",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "taskId", type: "uint256" },
      { name: "provider", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "BidSubmitted",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "deliveryDays", type: "uint256", indexed: false },
    ],
  },
] as const;

// ─── MatchingEngine ABI ──────────────────────────────────────────────────────
export const MATCHING_ENGINE_ABI = [
  {
    name: "runMatching",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "MatchingStarted",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "bidCount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "MatchingCompleted",
    type: "event",
    inputs: [
      { name: "taskId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "winningBid", type: "uint256", indexed: false },
    ],
  },
] as const;
